  - name: "Check if {{ package_name_caps }} is installed"
    package_facts:
      manager: "auto"
  - name: "{{ package_action_log }} {{ package_name_log }}"
#    when: nginx in ansible_facts.packages

    package:
      name: "{{ package_name }}"
      state: "{{ package_action }}"
      update_cache: yes
  - name: "{{ package_name }}"
      notify:
        nginx start
        nginx enable
        nginx restart
