---
-  name: "{{ gzip_log }} Install"
   package:
     name: "{{ gzip_package }}"
     state: latest
     update_cache: yes
   when: gzip_install
   tags:
     - install_gzip
     - deploy

-  name: "{{gzip_log}} Remove"
   package:
     name: "{{gzip_package}}"
     state: absent
     update_cache: yes
   when: gzip_remove and false 
   tags:
    - remove_gzip
    - erase
