---
-  name: "{{ nano_log }} Install"
   package:
     name: "{{ nano_package }}"
     state: latest
     update_cache: yes
   when: nano_install
   tags:
     - install_nano
     - deploy

-  name: "{{ nano_log }} Remove"
   package:
     name: "{{ nano_package }}"
     state: absent
     update_cache: yes
   when: nano_remove
   tags:
     - remove_nano
     - erase
