---
-  name: "{{ nginx_log }} Install"
   package:
     name: "{{ nginx_package }}"
     state: latest
     update_cache: yes
   when: nginx_install
   tags:
     - install_nginx
     - deploy

-  name: "{{ nginx_log }} Remove"
   package:
     name: "{{ nginx_package }}"
     state: absent
     update_cache: yes
   when: nginx_remove
   tags:
     - remove_nginx
     - erase

-  name: Start Nginx
   service: name=nginx state=started
   tags:
     - deploy
     - start_nginx

-  name: Stop Nginx
   service: name=nginx state=stopped
   tags:
     - stop_nginx


-  name: Restart Nginx
   service: name=nginx state=restarted
   tags:
     - restart_nginx
