---
#    - name: Add Nginx Repository
#      copy: src=nginx.repo dest=/etc/yum.repos.d/ owner=root group=root
#      register: nginx_repo
  - name: Install Nginx
    package:
      name: nginx 
      state: latest
      update_cache: yes
    notify:
           - nginx start

#    - name: Add NGINX cofig
#      when: nginxinstalled|success
#      template: src={{ domain }}.conf dest=/etc/nginx/conf.d/{{ domain }}.conf owner=nginx group=nginx
#
#    - name: Create Web Root
#      when: nginxinstalled|success
#      file: path={{ root }}  mode=775 state=directory owner=nginx group=nginx
#      notify:
#          - nginx restart
