---
-  name: "{{ unzip_log }} Install"
   package:
     name: "{{ unzip_package }}"
     state: latest
     update_cache: yes
   when: unzip_install
   tags:
     - install_unzip
     - deploy

-  name: "{{ unzip_log }} Remove"
   package:
     name: "{{ unzip_package }}"
     state: absent
     update_cache: yes
   when: unzip_remove
   tags:
     - remove_unzip
     - erase
