---
-  name: "{{ zip_log }} Install"
   package:
     name: "{{ zip_package }}"
     state: latest
     update_cache: yes
   when: zip_install
   tags:
     - install_zip
     - deploy

-  name: "{{ zip_log }} Remove"
   package:
     name: "{{ zip_package }}"
     state: absent
     update_cache: yes
   when: zip_remove
   tags:
     - remove_zip
     - erase
