---
   package_name: nginx
   package_name_caps: NGINX
   package_name_log: Nginx
   package_action: latest
   package_action_log: Install
   service_action: start

   install: true
   remove: false
   isStarting: true
   isEnabling: true
   isRestarting: true
   isStopping: false
#absent&Remove
#latest&Install
