  - name: "Check if NANO is installed"
    package_facts:
      manager: "auto"
  - name: "NANO test result"
    debug:
      msg: "NANO found"
    when: "'package_name' in ansible_facts.packages"
  - name: "NANO test result"
    debug:
      msg: "NANO NOT found"
    when: "'nano' not in ansible_facts.packages"

  - name: "{{ package_action_log }} {{ package_name }}"
    when:
    - ("'nano' in ansible_facts.packages") and (package_action == "absent")
    - ("'n' not in ansible_facts.packages") and (package_action == "latest")
    package:
      name: "{{ package_name }}"
      state: "{{ package_action }}"
      update_cache: yes
#    notify:
#           - "{{ package_name }} {{ service_action }}"
