---
    - name: nginx start
      #when: isStarting == true
      service: name=nginx state=started

    - name: nginx restart
      #when: isRestarting == true
      service: name=nginx state=restarted

    - name: nginx enable
      #when: isEnabling == true
      service: name=nginx state=enabled
